/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.34 from the
 * contents of SSD1306.xs. Do not edit this file, edit SSD1306.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "SSD1306.xs"
/*
 * SSD1306.xs file for RPi::OLED::SSD1306 Perl distribution
 *
 * Copyright (c) 2018 by Steve Bertrand
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the same terms as Perl itself, either Perl version 5.18.2 or, at your option,
 * any later version of Perl 5 you may have available.
 *
 */

#include <stdlib.h>
#include <stdint.h>

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
//#include "ppport.h"
//#include "INLINE.h"

#include "ssd1306_i2c.h"
#include <wiringPi.h>
#include <wiringPiI2C.h>

// #include <sys/mman.h>

// TESTING FOR GLOBAL VARS TO REPLACE CONSTS

int *buffer, xWIDTH, yHEIGHT;

void setup (int x, int y){

    xWIDTH = x;
    yHEIGHT = y;

    buffer = malloc(sizeof(int) * (xWIDTH * yHEIGHT));

    for (int i = 0; i < x*y; i++) {
        buffer[i] = i;
    }
}

void test (){
    printf("w: %d, h: %d\n", xWIDTH, yHEIGHT);

    for (int i=0; i<xWIDTH*yHEIGHT; i++){
        printf("%d\n", buffer[i]);
    }

    // reset the buffer

    memset(buffer, 0, xWIDTH * yHEIGHT * sizeof(int));

    // reprint it

    for (int i=0; i<xWIDTH*yHEIGHT; i++){
        printf("%d: %d\n", buffer[i], i);
    }
}

void done (){
    free(buffer);
}

#line 75 "SSD1306.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 219 "SSD1306.c"

XS_EUPXS(XS_RPi__OLED__SSD1306_setup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_setup)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "x, y");
    {
	int	x = (int)SvIV(ST(0))
;
	int	y = (int)SvIV(ST(1))
;

	setup(x, y);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_test); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_test)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	test();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_done); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_done)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	done();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_begin); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_begin)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "switchvcc, i2caddr");
    {
	unsigned int	switchvcc = (unsigned int)SvUV(ST(0))
;
	unsigned int	i2caddr = (unsigned int)SvUV(ST(1))
;

	ssd1306_begin(switchvcc, i2caddr);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_command); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_command)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "c");
    {
	unsigned int	c = (unsigned int)SvUV(ST(0))
;

	ssd1306_command(c);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_clearDisplay); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_clearDisplay)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	ssd1306_clearDisplay();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_invertDisplay); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_invertDisplay)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "i");
    {
	unsigned int	i = (unsigned int)SvUV(ST(0))
;

	ssd1306_invertDisplay(i);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_display); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_display)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	ssd1306_display();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_startscrollright); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_startscrollright)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "start, stop");
    {
	unsigned int	start = (unsigned int)SvUV(ST(0))
;
	unsigned int	stop = (unsigned int)SvUV(ST(1))
;

	ssd1306_startscrollright(start, stop);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_startscrollleft); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_startscrollleft)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "start, stop");
    {
	unsigned int	start = (unsigned int)SvUV(ST(0))
;
	unsigned int	stop = (unsigned int)SvUV(ST(1))
;

	ssd1306_startscrollleft(start, stop);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_startscrolldiagright); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_startscrolldiagright)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "start, stop");
    {
	unsigned int	start = (unsigned int)SvUV(ST(0))
;
	unsigned int	stop = (unsigned int)SvUV(ST(1))
;

	ssd1306_startscrolldiagright(start, stop);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_startscrolldiagleft); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_startscrolldiagleft)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "start, stop");
    {
	unsigned int	start = (unsigned int)SvUV(ST(0))
;
	unsigned int	stop = (unsigned int)SvUV(ST(1))
;

	ssd1306_startscrolldiagleft(start, stop);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_stopscroll); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_stopscroll)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	ssd1306_stopscroll();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_dim); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_dim)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "dim");
    {
	unsigned int	dim = (unsigned int)SvUV(ST(0))
;

	ssd1306_dim(dim);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawPixel); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawPixel)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "x, y, color");
    {
	int	x = (int)SvIV(ST(0))
;
	int	y = (int)SvIV(ST(1))
;
	unsigned int	color = (unsigned int)SvUV(ST(2))
;

	ssd1306_drawPixel(x, y, color);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawFastVLine); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawFastVLine)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "x, y, h, color");
    {
	int	x = (int)SvIV(ST(0))
;
	int	y = (int)SvIV(ST(1))
;
	int	h = (int)SvIV(ST(2))
;
	unsigned int	color = (unsigned int)SvUV(ST(3))
;

	ssd1306_drawFastVLine(x, y, h, color);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawFastHLine); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawFastHLine)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "x, y, w, color");
    {
	int	x = (int)SvIV(ST(0))
;
	int	y = (int)SvIV(ST(1))
;
	int	w = (int)SvIV(ST(2))
;
	unsigned int	color = (unsigned int)SvUV(ST(3))
;

	ssd1306_drawFastHLine(x, y, w, color);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_fillRect); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_fillRect)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "x, y, w, h, fillcolor");
    {
	int	x = (int)SvIV(ST(0))
;
	int	y = (int)SvIV(ST(1))
;
	int	w = (int)SvIV(ST(2))
;
	int	h = (int)SvIV(ST(3))
;
	int	fillcolor = (int)SvIV(ST(4))
;

	ssd1306_fillRect(x, y, w, h, fillcolor);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_setTextSize); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_setTextSize)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "s");
    {
	int	s = (int)SvIV(ST(0))
;

	ssd1306_setTextSize(s);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawString); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawString)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "str");
    {
	char *	str = (char *)SvPV_nolen(ST(0))
;

	ssd1306_drawString(str);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawChar); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_RPi__OLED__SSD1306_ssd1306_drawChar)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "x, y, c, color, size");
    {
	int	x = (int)SvIV(ST(0))
;
	int	y = (int)SvIV(ST(1))
;
	unsigned char	c = (unsigned char)SvUV(ST(2))
;
	int	color = (int)SvIV(ST(3))
;
	int	size = (int)SvIV(ST(4))
;

	ssd1306_drawChar(x, y, c, color, size);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_RPi__OLED__SSD1306); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_RPi__OLED__SSD1306)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("RPi::OLED::SSD1306::setup", XS_RPi__OLED__SSD1306_setup);
        newXS_deffile("RPi::OLED::SSD1306::test", XS_RPi__OLED__SSD1306_test);
        newXS_deffile("RPi::OLED::SSD1306::done", XS_RPi__OLED__SSD1306_done);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_begin", XS_RPi__OLED__SSD1306_ssd1306_begin);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_command", XS_RPi__OLED__SSD1306_ssd1306_command);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_clearDisplay", XS_RPi__OLED__SSD1306_ssd1306_clearDisplay);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_invertDisplay", XS_RPi__OLED__SSD1306_ssd1306_invertDisplay);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_display", XS_RPi__OLED__SSD1306_ssd1306_display);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_startscrollright", XS_RPi__OLED__SSD1306_ssd1306_startscrollright);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_startscrollleft", XS_RPi__OLED__SSD1306_ssd1306_startscrollleft);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_startscrolldiagright", XS_RPi__OLED__SSD1306_ssd1306_startscrolldiagright);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_startscrolldiagleft", XS_RPi__OLED__SSD1306_ssd1306_startscrolldiagleft);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_stopscroll", XS_RPi__OLED__SSD1306_ssd1306_stopscroll);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_dim", XS_RPi__OLED__SSD1306_ssd1306_dim);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_drawPixel", XS_RPi__OLED__SSD1306_ssd1306_drawPixel);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_drawFastVLine", XS_RPi__OLED__SSD1306_ssd1306_drawFastVLine);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_drawFastHLine", XS_RPi__OLED__SSD1306_ssd1306_drawFastHLine);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_fillRect", XS_RPi__OLED__SSD1306_ssd1306_fillRect);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_setTextSize", XS_RPi__OLED__SSD1306_ssd1306_setTextSize);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_drawString", XS_RPi__OLED__SSD1306_ssd1306_drawString);
        newXS_deffile("RPi::OLED::SSD1306::ssd1306_drawChar", XS_RPi__OLED__SSD1306_ssd1306_drawChar);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

